AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  python3.13
  Sample SAM Template for psychometric-test-lambda

Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Resources:
  myPsychometricTestFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64

      # —————— Variables de entorno ——————
      Environment:
        Variables:
          BUCKET_NAME: psychometrictest

      # —————— Permisos para S3 GetObject ——————
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource:
                - arn:aws:s3:::psychometrictest/*

    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./hello_world
      DockerTag: python3.13-v1

Outputs:
  myPsychometricTestFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt myPsychometricTestFunction.Arn

  myPsychometricTestFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt myPsychometricTestFunctionRole.Arn
